### ISSUE TITLE
Failed to load the minimap-split-diff package

### ISSUE THREAD

**Issue by questuk** [mupchrch/minimap-split-diff#7]
[Enter steps to reproduce:]

Added the following to my packages folder
-------------------------------------------
event-kit 2.3.0 
minimap-split-diff 0.3.7 
split-diff 1.3.0 

On starting atom I get the following error:

**Atom**: 1.16.0 ia32
**Electron**: 1.3.13
**OS**: Microsoft Windows 7 Professional 
**Thrown From**: [minimap-split-diff](https://github.com/mupchrch/minimap-split-diff) package 0.3.7

### Stack Trace

Failed to load the minimap-split-diff package

```
At Cannot find module 'event-kit'

Error: Cannot find module 'event-kit'
    at Module._resolveFilename (module.js:455:15)
    at Module._resolveFilename (~/AppData/Local/atom/app-1.16.0/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._resolveFilename (/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at /packages/minimap-split-diff-master/lib/minimap-split-diff.coffee:1:25)
    at /packages/minimap-split-diff-master/lib/minimap-split-diff.coffee:1:1)
    at Module._compile (/app.asar/src/native-compile-cache.js:109:30)
    at /app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (/app.asar/src/package.js:796:27)
    at /app.asar/src/package.js:123:28
    at Package.module.exports.Package.measure (/app.asar/src/package.js:96:15)
    at Package.module.exports.Package.load (/app.asar/src/package.js:110:12)
    at PackageManager.module.exports.PackageManager.loadPackage (/app.asar/src/package-manager.js:468:14)
    at /app.asar/src/package-manager.js:412:19
    at Config.module.exports.Config.transact (/app.asar/src/config.js:312:16)
    at PackageManager.module.exports.PackageManager.loadPackages (/app.asar/src/package-manager.js:407:19)
    at /app.asar/src/atom-environment.js:792:28
```

### Commands

```
```

### Non-Core Packages

```
event-kit 2.3.0 
minimap-split-diff 0.3.7 
split-diff 1.3.0 
```

**Comment by mupchrch** [comment]
So if you manually downloaded this package and put it in the packages folder, you probably need to run `apm install` on it. Looks like someone had a similar issue here https://github.com/Glavin001/atom-beautify/issues/626

**Comment by questuk** [comment]
Hi Mike,

Thanks for that, made me look again and how atom installs programs and found you can use 'Install Packages' under the Settings page.

Now it all works with no errors !

Regards

Gaz

**Comment by mupchrch** [comment]
Awesome!
