### ISSUE TITLE
Uncaught TypeError: Cannot read property 'decorateMarker' of null

### ISSUE THREAD

**Issue by theGhostJW** [mupchrch/minimap-split-diff#8]
**Steps to Reproduce**

1. Open 2 copies of a text file with the same content in L/R pane of Atom
2. Toggle MiniMap **ON**
3. Toggle SplitDiff **On**
4. Change some chars in left pane file
=> Change highlighted as expected in both SplitDiff and MiniMap
5. Toggle MiniMap **OFF**
6. Click / edit left pane to make chars the same again
=> BOOM (stack trace below)

**Atom**: 1.17.2 ia32
**Electron**: 1.3.15
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [minimap-split-diff](https://github.com/mupchrch/minimap-split-diff) package 0.3.7

### Stack Trace

Uncaught TypeError: Cannot read property 'decorateMarker' of null

```
At C:\Users\thegh\.atom\packages\minimap-split-diff\lib\minimap-split-diff-binding.coffee:52

TypeError: Cannot read property 'decorateMarker' of null
    at MinimapSplitDiffBinding.module.exports.MinimapSplitDiffBinding.createDecoration (/packages/minimap-split-diff/lib/minimap-split-diff-binding.coffee:52:33)
    at /packages/minimap-split-diff/lib/minimap-split-diff-binding.coffee:48:8
    at Array.forEach (native)
    at MinimapSplitDiffBinding.module.exports.MinimapSplitDiffBinding.handleMarkerLayer (/packages/minimap-split-diff/lib/minimap-split-diff-binding.coffee:47:30)
    at /packages/minimap-split-diff/lib/minimap-split-diff-binding.coffee:21:12
    at Function.module.exports.Emitter.simpleDispatch (~/AppData/Local/atom/app-1.17.2/resources/app/node_modules/event-kit/lib/emitter.js:25:1)
    at Emitter.module.exports.Emitter.emit (~/AppData/Local/atom/app-1.17.2/resources/app/node_modules/event-kit/lib/emitter.js:141:1)
    at DisplayMarkerLayer.module.exports.DisplayMarkerLayer.emitDidUpdate (~/AppData/Local/atom/app-1.17.2/resources/app/node_modules/text-buffer/lib/display-marker-layer.js:171:1)
    at Function.module.exports.Emitter.simpleDispatch (~/AppData/Local/atom/app-1.17.2/resources/app/node_modules/event-kit/lib/emitter.js:25:1)
    at Emitter.module.exports.Emitter.emit (~/AppData/Local/atom/app-1.17.2/resources/app/node_modules/event-kit/lib/emitter.js:141:1)
    at MarkerLayer.module.exports.MarkerLayer.emitUpdateEvent (~/AppData/Local/atom/app-1.17.2/resources/app/node_modules/text-buffer/lib/marker-layer.js:436:1)
    at TextBuffer.module.exports.TextBuffer.markersUpdated (~/AppData/Local/atom/app-1.17.2/resources/app/node_modules/text-buffer/lib/text-buffer.js:1534:1)
    at MarkerLayer.module.exports.MarkerLayer.createMarker (~/AppData/Local/atom/app-1.17.2/resources/app/node_modules/text-buffer/lib/marker-layer.js:414:1)
    at MarkerLayer.module.exports.MarkerLayer.markRange (~/AppData/Local/atom/app-1.17.2/resources/app/node_modules/text-buffer/lib/marker-layer.js:217:1)
    at DisplayMarkerLayer.module.exports.DisplayMarkerLayer.markBufferRange (~/AppData/Local/atom/app-1.17.2/resources/app/node_modules/text-buffer/lib/display-marker-layer.js:105:1)
    at EditorDiffExtender._createLineMarker (/packages/split-diff/lib/editor-diff-extender.js:227:30)
    at EditorDiffExtender.highlightLines (/packages/split-diff/lib/editor-diff-extender.js:45:12)
    at DiffView.displayDiff (/packages/split-diff/lib/diff-view.js:59:33)
    at Object._resumeUpdateDiff (/packages/split-diff/lib/split-diff.coffee:316:15)
    at /packages/split-diff/lib/split-diff.coffee:289:8
    at Socket.<anonymous> (~/AppData/Local/atom/app-1.17.2/resources/app/src/buffered-process.js:212:1)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at Pipe.onread (net.js:543:20)
```

### Commands

```
     -3:11.5.0 minimap:toggle (input.hidden-input)
     -3:07.8.0 core:backspace (input.hidden-input)
 12x -2:57.8.0 minimap:toggle (input.hidden-input)
     -2:34.1.0 core:backspace (input.hidden-input)
  2x -2:06.7.0 split-diff:toggle (div.scroll-view)
     -1:40.4.0 core:backspace (input.hidden-input)
     -1:38.5.0 intentions:highlight (input.hidden-input)
     -1:38.3.0 core:save (input.hidden-input)
     -1:33.9.0 minimap:toggle (div.scroll-view)
     -1:08.6.0 split-diff:toggle (div.scroll-view)
     -1:04.6.0 core:backspace (input.hidden-input)
     -0:55.7.0 split-diff:toggle (div.scroll-view)
  2x -0:51.8.0 core:backspace (input.hidden-input)
     -0:35.8.0 minimap:toggle (div.scroll-view)
     -0:29.7.0 core:backspace (input.hidden-input)
     -0:13.8.0 minimap:toggle (div.scroll-view)
```

### Non-Core Packages

```
atom-save-all 0.4.1 
autocomplete-haskell 0.7.2 
browser-plus 0.0.87 
busy-signal 1.4.3 
drag-drop-text 0.1.4 
haskell-debug 0.2.2 
haskell-ghc-mod 1.19.9 
haskell-hoogle 0.1.3 
hey-pane 1.0.0 
highlight-selected 0.13.1 
hyperclick 0.0.40 
ide-haskell 1.9.6 
ide-haskell-cabal 1.9.2 
ide-haskell-hasktags 0.0.11 
ide-haskell-repl 0.6.0 
ide-purescript 0.17.2 
intentions 1.1.2 
language-haskell 1.12.1 
language-purescript 0.8.2 
linter 2.1.4 
linter-ui-default 1.6.0 
markdown-scroll-sync 2.1.2 
minimap 4.28.2 
minimap-highlight-selected 4.6.1 
minimap-split-diff 0.3.7 
navigation-history 0.1.8 
npm 2.0.0 
open-recent 5.0.0 
path-copy 0.14.0 
platformio-ide-terminal 2.5.1 
script 3.15.0 
split-diff 1.4.0 
tablr 1.8.3 
tomatimer 1.2.3 
vertical-tabs 1.0.5 
```

**Comment by ghost** [comment]
I have the same issue.

I noticed that the minimap's splitdiff option doesn't work if the splitdiff's "override highlight color" option is set to true, and also the minimap splitdiff doesn't change its color if the "override highlith color" option is set to true while the minimap's splitdiff option is already enabled.

I encountered different ways in which the bug appeared: it was always related to the option "override highlight color" and the minimap.

**Comment by Amxx** [comment]
Getting the same error here. Has this bug been here for over 2 years ?
